// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1JDaBGI6Fa-1OBIA3sAU0eYC4nVgKJg',
    appId: '1:846744427579:web:fda1a6724f2dba0394501e',
    messagingSenderId: '846744427579',
    projectId: 'flutter-login-9d7b6',
    authDomain: 'flutter-login-9d7b6.firebaseapp.com',
    storageBucket: 'flutter-login-9d7b6.appspot.com',
    measurementId: 'G-V4DV58KJ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwenZFmtIJyL-JZY1tvdVydlMPXa1lkjs',
    appId: '1:846744427579:android:f07d068f2feac5ea94501e',
    messagingSenderId: '846744427579',
    projectId: 'flutter-login-9d7b6',
    storageBucket: 'flutter-login-9d7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjQjLRzjCZdc47seP-eU5C3PSe8DtSPY',
    appId: '1:846744427579:ios:df771589e86e03ef94501e',
    messagingSenderId: '846744427579',
    projectId: 'flutter-login-9d7b6',
    storageBucket: 'flutter-login-9d7b6.appspot.com',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjQjLRzjCZdc47seP-eU5C3PSe8DtSPY',
    appId: '1:846744427579:ios:3b4742b841ec538b94501e',
    messagingSenderId: '846744427579',
    projectId: 'flutter-login-9d7b6',
    storageBucket: 'flutter-login-9d7b6.appspot.com',
    iosBundleId: 'com.example.jobFinder.RunnerTests',
  );
}
